# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from arbiter.v1 import capability_pb2 as arbiter_dot_v1_dot_capability__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in arbiter/v1/capability_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CapabilityServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCapabilities = channel.unary_unary(
                '/arbiter.v1.CapabilityService/GetCapabilities',
                request_serializer=arbiter_dot_v1_dot_capability__pb2.GetCapabilitiesRequest.SerializeToString,
                response_deserializer=arbiter_dot_v1_dot_capability__pb2.GetCapabilitiesResponse.FromString,
                _registered_method=True)
        self.LoadSource = channel.unary_unary(
                '/arbiter.v1.CapabilityService/LoadSource',
                request_serializer=arbiter_dot_v1_dot_capability__pb2.LoadSourceRequest.SerializeToString,
                response_deserializer=arbiter_dot_v1_dot_capability__pb2.LoadSourceResponse.FromString,
                _registered_method=True)
        self.DeliverOutcome = channel.unary_unary(
                '/arbiter.v1.CapabilityService/DeliverOutcome',
                request_serializer=arbiter_dot_v1_dot_capability__pb2.DeliverOutcomeRequest.SerializeToString,
                response_deserializer=arbiter_dot_v1_dot_capability__pb2.DeliverOutcomeResponse.FromString,
                _registered_method=True)
        self.ExecuteWorker = channel.unary_unary(
                '/arbiter.v1.CapabilityService/ExecuteWorker',
                request_serializer=arbiter_dot_v1_dot_capability__pb2.ExecuteWorkerRequest.SerializeToString,
                response_deserializer=arbiter_dot_v1_dot_capability__pb2.ExecuteWorkerResponse.FromString,
                _registered_method=True)


class CapabilityServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadSource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeliverOutcome(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteWorker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CapabilityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=arbiter_dot_v1_dot_capability__pb2.GetCapabilitiesRequest.FromString,
                    response_serializer=arbiter_dot_v1_dot_capability__pb2.GetCapabilitiesResponse.SerializeToString,
            ),
            'LoadSource': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadSource,
                    request_deserializer=arbiter_dot_v1_dot_capability__pb2.LoadSourceRequest.FromString,
                    response_serializer=arbiter_dot_v1_dot_capability__pb2.LoadSourceResponse.SerializeToString,
            ),
            'DeliverOutcome': grpc.unary_unary_rpc_method_handler(
                    servicer.DeliverOutcome,
                    request_deserializer=arbiter_dot_v1_dot_capability__pb2.DeliverOutcomeRequest.FromString,
                    response_serializer=arbiter_dot_v1_dot_capability__pb2.DeliverOutcomeResponse.SerializeToString,
            ),
            'ExecuteWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteWorker,
                    request_deserializer=arbiter_dot_v1_dot_capability__pb2.ExecuteWorkerRequest.FromString,
                    response_serializer=arbiter_dot_v1_dot_capability__pb2.ExecuteWorkerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arbiter.v1.CapabilityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('arbiter.v1.CapabilityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CapabilityService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arbiter.v1.CapabilityService/GetCapabilities',
            arbiter_dot_v1_dot_capability__pb2.GetCapabilitiesRequest.SerializeToString,
            arbiter_dot_v1_dot_capability__pb2.GetCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arbiter.v1.CapabilityService/LoadSource',
            arbiter_dot_v1_dot_capability__pb2.LoadSourceRequest.SerializeToString,
            arbiter_dot_v1_dot_capability__pb2.LoadSourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeliverOutcome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arbiter.v1.CapabilityService/DeliverOutcome',
            arbiter_dot_v1_dot_capability__pb2.DeliverOutcomeRequest.SerializeToString,
            arbiter_dot_v1_dot_capability__pb2.DeliverOutcomeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arbiter.v1.CapabilityService/ExecuteWorker',
            arbiter_dot_v1_dot_capability__pb2.ExecuteWorkerRequest.SerializeToString,
            arbiter_dot_v1_dot_capability__pb2.ExecuteWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
