// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: arbiter/v1/capability.proto

package arbiterv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CapabilityService_GetCapabilities_FullMethodName = "/arbiter.v1.CapabilityService/GetCapabilities"
	CapabilityService_LoadSource_FullMethodName      = "/arbiter.v1.CapabilityService/LoadSource"
	CapabilityService_DeliverOutcome_FullMethodName  = "/arbiter.v1.CapabilityService/DeliverOutcome"
	CapabilityService_ExecuteWorker_FullMethodName   = "/arbiter.v1.CapabilityService/ExecuteWorker"
)

// CapabilityServiceClient is the client API for CapabilityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CapabilityServiceClient interface {
	GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error)
	LoadSource(ctx context.Context, in *LoadSourceRequest, opts ...grpc.CallOption) (*LoadSourceResponse, error)
	DeliverOutcome(ctx context.Context, in *DeliverOutcomeRequest, opts ...grpc.CallOption) (*DeliverOutcomeResponse, error)
	ExecuteWorker(ctx context.Context, in *ExecuteWorkerRequest, opts ...grpc.CallOption) (*ExecuteWorkerResponse, error)
}

type capabilityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCapabilityServiceClient(cc grpc.ClientConnInterface) CapabilityServiceClient {
	return &capabilityServiceClient{cc}
}

func (c *capabilityServiceClient) GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCapabilitiesResponse)
	err := c.cc.Invoke(ctx, CapabilityService_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capabilityServiceClient) LoadSource(ctx context.Context, in *LoadSourceRequest, opts ...grpc.CallOption) (*LoadSourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadSourceResponse)
	err := c.cc.Invoke(ctx, CapabilityService_LoadSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capabilityServiceClient) DeliverOutcome(ctx context.Context, in *DeliverOutcomeRequest, opts ...grpc.CallOption) (*DeliverOutcomeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliverOutcomeResponse)
	err := c.cc.Invoke(ctx, CapabilityService_DeliverOutcome_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capabilityServiceClient) ExecuteWorker(ctx context.Context, in *ExecuteWorkerRequest, opts ...grpc.CallOption) (*ExecuteWorkerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteWorkerResponse)
	err := c.cc.Invoke(ctx, CapabilityService_ExecuteWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CapabilityServiceServer is the server API for CapabilityService service.
// All implementations must embed UnimplementedCapabilityServiceServer
// for forward compatibility.
type CapabilityServiceServer interface {
	GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error)
	LoadSource(context.Context, *LoadSourceRequest) (*LoadSourceResponse, error)
	DeliverOutcome(context.Context, *DeliverOutcomeRequest) (*DeliverOutcomeResponse, error)
	ExecuteWorker(context.Context, *ExecuteWorkerRequest) (*ExecuteWorkerResponse, error)
	mustEmbedUnimplementedCapabilityServiceServer()
}

// UnimplementedCapabilityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCapabilityServiceServer struct{}

func (UnimplementedCapabilityServiceServer) GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedCapabilityServiceServer) LoadSource(context.Context, *LoadSourceRequest) (*LoadSourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadSource not implemented")
}
func (UnimplementedCapabilityServiceServer) DeliverOutcome(context.Context, *DeliverOutcomeRequest) (*DeliverOutcomeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeliverOutcome not implemented")
}
func (UnimplementedCapabilityServiceServer) ExecuteWorker(context.Context, *ExecuteWorkerRequest) (*ExecuteWorkerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteWorker not implemented")
}
func (UnimplementedCapabilityServiceServer) mustEmbedUnimplementedCapabilityServiceServer() {}
func (UnimplementedCapabilityServiceServer) testEmbeddedByValue()                           {}

// UnsafeCapabilityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CapabilityServiceServer will
// result in compilation errors.
type UnsafeCapabilityServiceServer interface {
	mustEmbedUnimplementedCapabilityServiceServer()
}

func RegisterCapabilityServiceServer(s grpc.ServiceRegistrar, srv CapabilityServiceServer) {
	// If the following call pancis, it indicates UnimplementedCapabilityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CapabilityService_ServiceDesc, srv)
}

func _CapabilityService_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapabilityServiceServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapabilityService_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapabilityServiceServer).GetCapabilities(ctx, req.(*GetCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CapabilityService_LoadSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapabilityServiceServer).LoadSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapabilityService_LoadSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapabilityServiceServer).LoadSource(ctx, req.(*LoadSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CapabilityService_DeliverOutcome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliverOutcomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapabilityServiceServer).DeliverOutcome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapabilityService_DeliverOutcome_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapabilityServiceServer).DeliverOutcome(ctx, req.(*DeliverOutcomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CapabilityService_ExecuteWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapabilityServiceServer).ExecuteWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapabilityService_ExecuteWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapabilityServiceServer).ExecuteWorker(ctx, req.(*ExecuteWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CapabilityService_ServiceDesc is the grpc.ServiceDesc for CapabilityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CapabilityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arbiter.v1.CapabilityService",
	HandlerType: (*CapabilityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCapabilities",
			Handler:    _CapabilityService_GetCapabilities_Handler,
		},
		{
			MethodName: "LoadSource",
			Handler:    _CapabilityService_LoadSource_Handler,
		},
		{
			MethodName: "DeliverOutcome",
			Handler:    _CapabilityService_DeliverOutcome_Handler,
		},
		{
			MethodName: "ExecuteWorker",
			Handler:    _CapabilityService_ExecuteWorker_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "arbiter/v1/capability.proto",
}
