// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: arbiter/v1/capability.proto

package arbiterv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerOutputKind int32

const (
	WorkerOutputKind_WORKER_OUTPUT_KIND_UNSPECIFIED WorkerOutputKind = 0
	WorkerOutputKind_WORKER_OUTPUT_KIND_FACT        WorkerOutputKind = 1
	WorkerOutputKind_WORKER_OUTPUT_KIND_OUTCOME     WorkerOutputKind = 2
)

// Enum value maps for WorkerOutputKind.
var (
	WorkerOutputKind_name = map[int32]string{
		0: "WORKER_OUTPUT_KIND_UNSPECIFIED",
		1: "WORKER_OUTPUT_KIND_FACT",
		2: "WORKER_OUTPUT_KIND_OUTCOME",
	}
	WorkerOutputKind_value = map[string]int32{
		"WORKER_OUTPUT_KIND_UNSPECIFIED": 0,
		"WORKER_OUTPUT_KIND_FACT":        1,
		"WORKER_OUTPUT_KIND_OUTCOME":     2,
	}
)

func (x WorkerOutputKind) Enum() *WorkerOutputKind {
	p := new(WorkerOutputKind)
	*p = x
	return p
}

func (x WorkerOutputKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkerOutputKind) Descriptor() protoreflect.EnumDescriptor {
	return file_arbiter_v1_capability_proto_enumTypes[0].Descriptor()
}

func (WorkerOutputKind) Type() protoreflect.EnumType {
	return &file_arbiter_v1_capability_proto_enumTypes[0]
}

func (x WorkerOutputKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkerOutputKind.Descriptor instead.
func (WorkerOutputKind) EnumDescriptor() ([]byte, []int) {
	return file_arbiter_v1_capability_proto_rawDescGZIP(), []int{0}
}

type GetCapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapabilitiesRequest) Reset() {
	*x = GetCapabilitiesRequest{}
	mi := &file_arbiter_v1_capability_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesRequest) ProtoMessage() {}

func (x *GetCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_capability_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_capability_proto_rawDescGZIP(), []int{0}
}

type SourceCapability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scheme        string                 `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceCapability) Reset() {
	*x = SourceCapability{}
	mi := &file_arbiter_v1_capability_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceCapability) ProtoMessage() {}

func (x *SourceCapability) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_capability_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceCapability.ProtoReflect.Descriptor instead.
func (*SourceCapability) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_capability_proto_rawDescGZIP(), []int{1}
}

func (x *SourceCapability) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *SourceCapability) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type SinkCapability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SinkCapability) Reset() {
	*x = SinkCapability{}
	mi := &file_arbiter_v1_capability_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SinkCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SinkCapability) ProtoMessage() {}

func (x *SinkCapability) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_capability_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SinkCapability.ProtoReflect.Descriptor instead.
func (*SinkCapability) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_capability_proto_rawDescGZIP(), []int{2}
}

func (x *SinkCapability) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SinkCapability) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type WorkerCapability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerCapability) Reset() {
	*x = WorkerCapability{}
	mi := &file_arbiter_v1_capability_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerCapability) ProtoMessage() {}

func (x *WorkerCapability) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_capability_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerCapability.ProtoReflect.Descriptor instead.
func (*WorkerCapability) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_capability_proto_rawDescGZIP(), []int{3}
}

func (x *WorkerCapability) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *WorkerCapability) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetCapabilitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Sources       []*SourceCapability    `protobuf:"bytes,3,rep,name=sources,proto3" json:"sources,omitempty"`
	Sinks         []*SinkCapability      `protobuf:"bytes,4,rep,name=sinks,proto3" json:"sinks,omitempty"`
	Workers       []*WorkerCapability    `protobuf:"bytes,5,rep,name=workers,proto3" json:"workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapabilitiesResponse) Reset() {
	*x = GetCapabilitiesResponse{}
	mi := &file_arbiter_v1_capability_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesResponse) ProtoMessage() {}

func (x *GetCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_capability_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_capability_proto_rawDescGZIP(), []int{4}
}

func (x *GetCapabilitiesResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetCapabilitiesResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetCapabilitiesResponse) GetSources() []*SourceCapability {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *GetCapabilitiesResponse) GetSinks() []*SinkCapability {
	if x != nil {
		return x.Sinks
	}
	return nil
}

func (x *GetCapabilitiesResponse) GetWorkers() []*WorkerCapability {
	if x != nil {
		return x.Workers
	}
	return nil
}

type LoadSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadSourceRequest) Reset() {
	*x = LoadSourceRequest{}
	mi := &file_arbiter_v1_capability_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadSourceRequest) ProtoMessage() {}

func (x *LoadSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_capability_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadSourceRequest.ProtoReflect.Descriptor instead.
func (*LoadSourceRequest) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_capability_proto_rawDescGZIP(), []int{5}
}

func (x *LoadSourceRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type LoadSourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Facts         []*ExpertFact          `protobuf:"bytes,1,rep,name=facts,proto3" json:"facts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadSourceResponse) Reset() {
	*x = LoadSourceResponse{}
	mi := &file_arbiter_v1_capability_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadSourceResponse) ProtoMessage() {}

func (x *LoadSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_capability_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadSourceResponse.ProtoReflect.Descriptor instead.
func (*LoadSourceResponse) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_capability_proto_rawDescGZIP(), []int{6}
}

func (x *LoadSourceResponse) GetFacts() []*ExpertFact {
	if x != nil {
		return x.Facts
	}
	return nil
}

type DeliveryContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId    string                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	ArbiterName   string                 `protobuf:"bytes,2,opt,name=arbiter_name,json=arbiterName,proto3" json:"arbiter_name,omitempty"`
	WorkerName    string                 `protobuf:"bytes,3,opt,name=worker_name,json=workerName,proto3" json:"worker_name,omitempty"`
	HandlerKind   string                 `protobuf:"bytes,4,opt,name=handler_kind,json=handlerKind,proto3" json:"handler_kind,omitempty"`
	HandlerTarget string                 `protobuf:"bytes,5,opt,name=handler_target,json=handlerTarget,proto3" json:"handler_target,omitempty"`
	Outcome       *ExpertOutcome         `protobuf:"bytes,6,opt,name=outcome,proto3" json:"outcome,omitempty"`
	Attempt       uint32                 `protobuf:"varint,7,opt,name=attempt,proto3" json:"attempt,omitempty"`
	EnqueuedAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=enqueued_at,json=enqueuedAt,proto3" json:"enqueued_at,omitempty"`
	LastAttemptAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_attempt_at,json=lastAttemptAt,proto3" json:"last_attempt_at,omitempty"`
	NextAttemptAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=next_attempt_at,json=nextAttemptAt,proto3" json:"next_attempt_at,omitempty"`
	LastError     string                 `protobuf:"bytes,11,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryContext) Reset() {
	*x = DeliveryContext{}
	mi := &file_arbiter_v1_capability_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryContext) ProtoMessage() {}

func (x *DeliveryContext) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_capability_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryContext.ProtoReflect.Descriptor instead.
func (*DeliveryContext) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_capability_proto_rawDescGZIP(), []int{7}
}

func (x *DeliveryContext) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *DeliveryContext) GetArbiterName() string {
	if x != nil {
		return x.ArbiterName
	}
	return ""
}

func (x *DeliveryContext) GetWorkerName() string {
	if x != nil {
		return x.WorkerName
	}
	return ""
}

func (x *DeliveryContext) GetHandlerKind() string {
	if x != nil {
		return x.HandlerKind
	}
	return ""
}

func (x *DeliveryContext) GetHandlerTarget() string {
	if x != nil {
		return x.HandlerTarget
	}
	return ""
}

func (x *DeliveryContext) GetOutcome() *ExpertOutcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *DeliveryContext) GetAttempt() uint32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *DeliveryContext) GetEnqueuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EnqueuedAt
	}
	return nil
}

func (x *DeliveryContext) GetLastAttemptAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAttemptAt
	}
	return nil
}

func (x *DeliveryContext) GetNextAttemptAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextAttemptAt
	}
	return nil
}

func (x *DeliveryContext) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type DeliverOutcomeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivery      *DeliveryContext       `protobuf:"bytes,1,opt,name=delivery,proto3" json:"delivery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverOutcomeRequest) Reset() {
	*x = DeliverOutcomeRequest{}
	mi := &file_arbiter_v1_capability_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverOutcomeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverOutcomeRequest) ProtoMessage() {}

func (x *DeliverOutcomeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_capability_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverOutcomeRequest.ProtoReflect.Descriptor instead.
func (*DeliverOutcomeRequest) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_capability_proto_rawDescGZIP(), []int{8}
}

func (x *DeliverOutcomeRequest) GetDelivery() *DeliveryContext {
	if x != nil {
		return x.Delivery
	}
	return nil
}

type DeliverOutcomeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverOutcomeResponse) Reset() {
	*x = DeliverOutcomeResponse{}
	mi := &file_arbiter_v1_capability_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverOutcomeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverOutcomeResponse) ProtoMessage() {}

func (x *DeliverOutcomeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_capability_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverOutcomeResponse.ProtoReflect.Descriptor instead.
func (*DeliverOutcomeResponse) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_capability_proto_rawDescGZIP(), []int{9}
}

type WorkerSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Input         string                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	OutputKind    WorkerOutputKind       `protobuf:"varint,4,opt,name=output_kind,json=outputKind,proto3,enum=arbiter.v1.WorkerOutputKind" json:"output_kind,omitempty"`
	Kind          string                 `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	Target        string                 `protobuf:"bytes,6,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerSpec) Reset() {
	*x = WorkerSpec{}
	mi := &file_arbiter_v1_capability_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerSpec) ProtoMessage() {}

func (x *WorkerSpec) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_capability_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerSpec.ProtoReflect.Descriptor instead.
func (*WorkerSpec) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_capability_proto_rawDescGZIP(), []int{10}
}

func (x *WorkerSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkerSpec) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *WorkerSpec) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *WorkerSpec) GetOutputKind() WorkerOutputKind {
	if x != nil {
		return x.OutputKind
	}
	return WorkerOutputKind_WORKER_OUTPUT_KIND_UNSPECIFIED
}

func (x *WorkerSpec) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *WorkerSpec) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type ExecuteWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Worker        *WorkerSpec            `protobuf:"bytes,1,opt,name=worker,proto3" json:"worker,omitempty"`
	Delivery      *DeliveryContext       `protobuf:"bytes,2,opt,name=delivery,proto3" json:"delivery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteWorkerRequest) Reset() {
	*x = ExecuteWorkerRequest{}
	mi := &file_arbiter_v1_capability_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteWorkerRequest) ProtoMessage() {}

func (x *ExecuteWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_capability_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteWorkerRequest.ProtoReflect.Descriptor instead.
func (*ExecuteWorkerRequest) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_capability_proto_rawDescGZIP(), []int{11}
}

func (x *ExecuteWorkerRequest) GetWorker() *WorkerSpec {
	if x != nil {
		return x.Worker
	}
	return nil
}

func (x *ExecuteWorkerRequest) GetDelivery() *DeliveryContext {
	if x != nil {
		return x.Delivery
	}
	return nil
}

type ExecuteWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Facts         []*ExpertFact          `protobuf:"bytes,1,rep,name=facts,proto3" json:"facts,omitempty"`
	Outcomes      []*ExpertOutcome       `protobuf:"bytes,2,rep,name=outcomes,proto3" json:"outcomes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteWorkerResponse) Reset() {
	*x = ExecuteWorkerResponse{}
	mi := &file_arbiter_v1_capability_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteWorkerResponse) ProtoMessage() {}

func (x *ExecuteWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_arbiter_v1_capability_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteWorkerResponse.ProtoReflect.Descriptor instead.
func (*ExecuteWorkerResponse) Descriptor() ([]byte, []int) {
	return file_arbiter_v1_capability_proto_rawDescGZIP(), []int{12}
}

func (x *ExecuteWorkerResponse) GetFacts() []*ExpertFact {
	if x != nil {
		return x.Facts
	}
	return nil
}

func (x *ExecuteWorkerResponse) GetOutcomes() []*ExpertOutcome {
	if x != nil {
		return x.Outcomes
	}
	return nil
}

var File_arbiter_v1_capability_proto protoreflect.FileDescriptor

const file_arbiter_v1_capability_proto_rawDesc = "" +
	"\n" +
	"\x1barbiter/v1/capability.proto\x12\n" +
	"arbiter.v1\x1a\x18arbiter/v1/service.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x18\n" +
	"\x16GetCapabilitiesRequest\"L\n" +
	"\x10SourceCapability\x12\x16\n" +
	"\x06scheme\x18\x01 \x01(\tR\x06scheme\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"F\n" +
	"\x0eSinkCapability\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"H\n" +
	"\x10WorkerCapability\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\xe9\x01\n" +
	"\x17GetCapabilitiesResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x126\n" +
	"\asources\x18\x03 \x03(\v2\x1c.arbiter.v1.SourceCapabilityR\asources\x120\n" +
	"\x05sinks\x18\x04 \x03(\v2\x1a.arbiter.v1.SinkCapabilityR\x05sinks\x126\n" +
	"\aworkers\x18\x05 \x03(\v2\x1c.arbiter.v1.WorkerCapabilityR\aworkers\"+\n" +
	"\x11LoadSourceRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\"B\n" +
	"\x12LoadSourceResponse\x12,\n" +
	"\x05facts\x18\x01 \x03(\v2\x16.arbiter.v1.ExpertFactR\x05facts\"\xf3\x03\n" +
	"\x0fDeliveryContext\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\tR\n" +
	"deliveryId\x12!\n" +
	"\farbiter_name\x18\x02 \x01(\tR\varbiterName\x12\x1f\n" +
	"\vworker_name\x18\x03 \x01(\tR\n" +
	"workerName\x12!\n" +
	"\fhandler_kind\x18\x04 \x01(\tR\vhandlerKind\x12%\n" +
	"\x0ehandler_target\x18\x05 \x01(\tR\rhandlerTarget\x123\n" +
	"\aoutcome\x18\x06 \x01(\v2\x19.arbiter.v1.ExpertOutcomeR\aoutcome\x12\x18\n" +
	"\aattempt\x18\a \x01(\rR\aattempt\x12;\n" +
	"\venqueued_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"enqueuedAt\x12B\n" +
	"\x0flast_attempt_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\rlastAttemptAt\x12B\n" +
	"\x0fnext_attempt_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\rnextAttemptAt\x12\x1d\n" +
	"\n" +
	"last_error\x18\v \x01(\tR\tlastError\"P\n" +
	"\x15DeliverOutcomeRequest\x127\n" +
	"\bdelivery\x18\x01 \x01(\v2\x1b.arbiter.v1.DeliveryContextR\bdelivery\"\x18\n" +
	"\x16DeliverOutcomeResponse\"\xb9\x01\n" +
	"\n" +
	"WorkerSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05input\x18\x02 \x01(\tR\x05input\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\x12=\n" +
	"\voutput_kind\x18\x04 \x01(\x0e2\x1c.arbiter.v1.WorkerOutputKindR\n" +
	"outputKind\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\x12\x16\n" +
	"\x06target\x18\x06 \x01(\tR\x06target\"\x7f\n" +
	"\x14ExecuteWorkerRequest\x12.\n" +
	"\x06worker\x18\x01 \x01(\v2\x16.arbiter.v1.WorkerSpecR\x06worker\x127\n" +
	"\bdelivery\x18\x02 \x01(\v2\x1b.arbiter.v1.DeliveryContextR\bdelivery\"|\n" +
	"\x15ExecuteWorkerResponse\x12,\n" +
	"\x05facts\x18\x01 \x03(\v2\x16.arbiter.v1.ExpertFactR\x05facts\x125\n" +
	"\boutcomes\x18\x02 \x03(\v2\x19.arbiter.v1.ExpertOutcomeR\boutcomes*s\n" +
	"\x10WorkerOutputKind\x12\"\n" +
	"\x1eWORKER_OUTPUT_KIND_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17WORKER_OUTPUT_KIND_FACT\x10\x01\x12\x1e\n" +
	"\x1aWORKER_OUTPUT_KIND_OUTCOME\x10\x022\xeb\x02\n" +
	"\x11CapabilityService\x12Z\n" +
	"\x0fGetCapabilities\x12\".arbiter.v1.GetCapabilitiesRequest\x1a#.arbiter.v1.GetCapabilitiesResponse\x12K\n" +
	"\n" +
	"LoadSource\x12\x1d.arbiter.v1.LoadSourceRequest\x1a\x1e.arbiter.v1.LoadSourceResponse\x12W\n" +
	"\x0eDeliverOutcome\x12!.arbiter.v1.DeliverOutcomeRequest\x1a\".arbiter.v1.DeliverOutcomeResponse\x12T\n" +
	"\rExecuteWorker\x12 .arbiter.v1.ExecuteWorkerRequest\x1a!.arbiter.v1.ExecuteWorkerResponseB.Z,m31labs.dev/arbiter/api/arbiter/v1;arbiterv1b\x06proto3"

var (
	file_arbiter_v1_capability_proto_rawDescOnce sync.Once
	file_arbiter_v1_capability_proto_rawDescData []byte
)

func file_arbiter_v1_capability_proto_rawDescGZIP() []byte {
	file_arbiter_v1_capability_proto_rawDescOnce.Do(func() {
		file_arbiter_v1_capability_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_arbiter_v1_capability_proto_rawDesc), len(file_arbiter_v1_capability_proto_rawDesc)))
	})
	return file_arbiter_v1_capability_proto_rawDescData
}

var file_arbiter_v1_capability_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_arbiter_v1_capability_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_arbiter_v1_capability_proto_goTypes = []any{
	(WorkerOutputKind)(0),           // 0: arbiter.v1.WorkerOutputKind
	(*GetCapabilitiesRequest)(nil),  // 1: arbiter.v1.GetCapabilitiesRequest
	(*SourceCapability)(nil),        // 2: arbiter.v1.SourceCapability
	(*SinkCapability)(nil),          // 3: arbiter.v1.SinkCapability
	(*WorkerCapability)(nil),        // 4: arbiter.v1.WorkerCapability
	(*GetCapabilitiesResponse)(nil), // 5: arbiter.v1.GetCapabilitiesResponse
	(*LoadSourceRequest)(nil),       // 6: arbiter.v1.LoadSourceRequest
	(*LoadSourceResponse)(nil),      // 7: arbiter.v1.LoadSourceResponse
	(*DeliveryContext)(nil),         // 8: arbiter.v1.DeliveryContext
	(*DeliverOutcomeRequest)(nil),   // 9: arbiter.v1.DeliverOutcomeRequest
	(*DeliverOutcomeResponse)(nil),  // 10: arbiter.v1.DeliverOutcomeResponse
	(*WorkerSpec)(nil),              // 11: arbiter.v1.WorkerSpec
	(*ExecuteWorkerRequest)(nil),    // 12: arbiter.v1.ExecuteWorkerRequest
	(*ExecuteWorkerResponse)(nil),   // 13: arbiter.v1.ExecuteWorkerResponse
	(*ExpertFact)(nil),              // 14: arbiter.v1.ExpertFact
	(*ExpertOutcome)(nil),           // 15: arbiter.v1.ExpertOutcome
	(*timestamppb.Timestamp)(nil),   // 16: google.protobuf.Timestamp
}
var file_arbiter_v1_capability_proto_depIdxs = []int32{
	2,  // 0: arbiter.v1.GetCapabilitiesResponse.sources:type_name -> arbiter.v1.SourceCapability
	3,  // 1: arbiter.v1.GetCapabilitiesResponse.sinks:type_name -> arbiter.v1.SinkCapability
	4,  // 2: arbiter.v1.GetCapabilitiesResponse.workers:type_name -> arbiter.v1.WorkerCapability
	14, // 3: arbiter.v1.LoadSourceResponse.facts:type_name -> arbiter.v1.ExpertFact
	15, // 4: arbiter.v1.DeliveryContext.outcome:type_name -> arbiter.v1.ExpertOutcome
	16, // 5: arbiter.v1.DeliveryContext.enqueued_at:type_name -> google.protobuf.Timestamp
	16, // 6: arbiter.v1.DeliveryContext.last_attempt_at:type_name -> google.protobuf.Timestamp
	16, // 7: arbiter.v1.DeliveryContext.next_attempt_at:type_name -> google.protobuf.Timestamp
	8,  // 8: arbiter.v1.DeliverOutcomeRequest.delivery:type_name -> arbiter.v1.DeliveryContext
	0,  // 9: arbiter.v1.WorkerSpec.output_kind:type_name -> arbiter.v1.WorkerOutputKind
	11, // 10: arbiter.v1.ExecuteWorkerRequest.worker:type_name -> arbiter.v1.WorkerSpec
	8,  // 11: arbiter.v1.ExecuteWorkerRequest.delivery:type_name -> arbiter.v1.DeliveryContext
	14, // 12: arbiter.v1.ExecuteWorkerResponse.facts:type_name -> arbiter.v1.ExpertFact
	15, // 13: arbiter.v1.ExecuteWorkerResponse.outcomes:type_name -> arbiter.v1.ExpertOutcome
	1,  // 14: arbiter.v1.CapabilityService.GetCapabilities:input_type -> arbiter.v1.GetCapabilitiesRequest
	6,  // 15: arbiter.v1.CapabilityService.LoadSource:input_type -> arbiter.v1.LoadSourceRequest
	9,  // 16: arbiter.v1.CapabilityService.DeliverOutcome:input_type -> arbiter.v1.DeliverOutcomeRequest
	12, // 17: arbiter.v1.CapabilityService.ExecuteWorker:input_type -> arbiter.v1.ExecuteWorkerRequest
	5,  // 18: arbiter.v1.CapabilityService.GetCapabilities:output_type -> arbiter.v1.GetCapabilitiesResponse
	7,  // 19: arbiter.v1.CapabilityService.LoadSource:output_type -> arbiter.v1.LoadSourceResponse
	10, // 20: arbiter.v1.CapabilityService.DeliverOutcome:output_type -> arbiter.v1.DeliverOutcomeResponse
	13, // 21: arbiter.v1.CapabilityService.ExecuteWorker:output_type -> arbiter.v1.ExecuteWorkerResponse
	18, // [18:22] is the sub-list for method output_type
	14, // [14:18] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_arbiter_v1_capability_proto_init() }
func file_arbiter_v1_capability_proto_init() {
	if File_arbiter_v1_capability_proto != nil {
		return
	}
	file_arbiter_v1_service_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_arbiter_v1_capability_proto_rawDesc), len(file_arbiter_v1_capability_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_arbiter_v1_capability_proto_goTypes,
		DependencyIndexes: file_arbiter_v1_capability_proto_depIdxs,
		EnumInfos:         file_arbiter_v1_capability_proto_enumTypes,
		MessageInfos:      file_arbiter_v1_capability_proto_msgTypes,
	}.Build()
	File_arbiter_v1_capability_proto = out.File
	file_arbiter_v1_capability_proto_goTypes = nil
	file_arbiter_v1_capability_proto_depIdxs = nil
}
